spring:

  application:
    name: trust-treatment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: '0616'

server:
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.tusttreatment.pojo.entity,com.example.subscribe.pojo.vo,com.example.subscribe.pojo.qo
